FROM jboss/keycloak
ENV KEYCLOAK_USER=admin
ENV KEYCLOAK_PASSWORD=password
COPY setup-keycloak.sh.custom /tmp/setup-keycloak.sh
COPY setup-kc-client-liberty.sh /tmp/setup-kc-client-liberty.sh
COPY setup-kc-client-was90.sh /tmp/setup-kc-client-was90.sh
