apiVersion: apps/v1
kind: Deployment
metadata:
  name: saml-deployment
  labels:
    app: saml
spec:
  selector:
    matchLabels:
      app: saml
  template:
    metadata:
      labels:
        app: saml
    spec:
      volumes:
      - name: shared-data
        emptyDir: {}
      containers:
      - name: saml-container
        image: image-registry.openshift-image-registry.svc:5000/[project-name]/saml:[build-date]
        volumeMounts:
        - name: shared-data
          mountPath: /samlf
        ports:
        - containerPort: 9080
      - name: ubuntu-container
        image: image-registry.openshift-image-registry.svc:5000/[project-name]/ubuntu:latest
        volumeMounts:
        - name: shared-data
          mountPath: /samlf
        command: ["/bin/sh"]
        args: ["-c", "mkdir -p /samlf/share; chown -R 1001:0 /samlf/; while true; do sleep 600; done"]
      imagePullSecrets:
      - name: docker-user-secret
--- 
apiVersion: v1
kind: Service
metadata:
  name: saml-service
spec:
  selector:
    app: saml
  ports:
  - protocol: TCP
    port: 9080
---
apiVersion: v1
kind: Route
metadata:
  name: saml-route
spec:
  to:
    kind: Service
    name: saml-service

    https://docs.openshift.com/container-platform/4.6/networking/routes/secured-routes.html
