apiVersion: apps/v1
kind: Deployment
metadata:
  name: saml-deployment
  labels:
    app: saml
spec:
  selector:
    matchLabels:
      app: saml
  template:
    metadata:
      labels:
        app: saml
    spec:
      containers:
      - name: saml-container
        image: image-registry.openshift-image-registry.svc:5000/[project-name]/saml:[build-date]
        ports:
        - containerPort: 9080
      imagePullSecrets:
      - name: docker-user-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: idp-deployment
  labels:
    app: idp
spec:
  selector:
    matchLabels:
      app: idp
  template:
    metadata:
      labels:
        app: idp
    spec:
      containers:
      - name: idp-container
        image: image-registry.openshift-image-registry.svc:5000/[project-name]/idp:[build-date]
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: docker-user-secret
--- 
apiVersion: v1
kind: Service
metadata:
  name: saml-service
spec:
  selector:
    app: saml
  ports:
  - protocol: TCP
    port: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: idp-service
spec:
  selector:
    app: saml
  ports:
  - protocol: TCP
    port: 8080
---
apiVersion: v1
kind: Route
metadata:
  name: saml-route
spec:
  to:
    kind: Service
    name: saml-service
---
apiVersion: v1
kind: Route
metadata:
  name: idp-route
spec:
  to:
    kind: Service
    name: idp-service
