apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth
spec:
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth-container
        image: image-registry.openshift-image-registry.svc:5000/[project-name]/auth:[build-date]
        ports:
        - containerPort: 9080
      imagePullSecrets:
      - name: docker-user-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap-deployment
  labels:
    app: ldap
spec:
  selector:
    matchLabels:
      app: ldap
  template:
    metadata:
      labels:
        app: ldap
    spec:
      containers:
      - name: ldap-container
        image: image-registry.openshift-image-registry.svc:5000/[project-name]/ldap:[build-date]
        ports:
        - containerPort: 389
      imagePullSecrets:
      - name: docker-user-secret
--- 
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
  - protocol: TCP
    port: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: ldap-service
spec:
  selector:
    app: ldap
  ports:
  - protocol: TCP
    port: 389
---
apiVersion: v1
kind: Route
metadata:
  name: auth-route
spec:
  to:
    kind: Service
    name: auth-service
